### ISSUE TITLE
Spelling mistake in README

### ISSUE THREAD

**Issue by maciekkoz98** [GrzesiuKo/ProductTrackerWeb#1]
In your readme I found an error in the ProductTrackerWeb section. (inforamtion instead of information) Please correct it :)

@GrzesiuKo masz ty rozum i godność człowieka? Takie błędy popełniać?
Pozdrawiamy z wykładu z Ochrony Danych,
Oburzeni Puryści Językowi
Plujemy na Ciebie, tfu

**Comment by PatrykZaniewski** [comment]
Ahh proszę państwa, tragedia, źle, FATALNIE!!!

**Comment by MateuszCiupa** [comment]
# 
## 
- ### **_~~yyy~~ _ **

**Comment by KonradMagiera** [comment]
Halo, wie geht's?

**Comment by PatrykZaniewski** [comment]
Halooooo (╯°□°）╯︵ ┻━┻

**Comment by JCeluch** [comment]
Ło panie… co to się stanęło?

**Comment by matsmolinski** [comment]
Życie nie polega na zdobywaniu punktów

**Comment by GrzesiuKo** [comment]
Szanowni Państwo,
Bardzo dziękujemy za zainteresowanie i profesjonalne zgłoszenie błędu.
Odpowiednie kroki zostały już podjęte, aby przywrócić wspomnianą czystość języka.

Mit freundlichen Grüßen,
Grzesiu von Ko

**Comment by maciekkoz98** [comment]
Rasowa czystość języka! Sehr gut!
